import { RoleType } from '@prisma/client';

export interface PermissionItem {
  code: string;
  name: string;
  description: string;
  isPage?: boolean;
}

export interface PermissionModule {
  id: string;
  name: string;
  description: string;
  pageCode: string;
  permissions: PermissionItem[];
}

export const PERMISSION_MODULES: PermissionModule[] = [
  {
    id: 'dashboard',
    name: 'Bosh Panel (Dashboard)',
    description: 'Umumiy tahlil, statistik ko‘rsatkichlar va grafiklar',
    pageCode: 'page:dashboard',
    permissions: [
      { code: 'page:dashboard', name: 'Sahifaga kirish', description: 'Bosh panelga kirish huquqi', isPage: true },
      { code: 'dashboard:view_stats', name: 'Statistikalarni ko‘rish', description: 'Asosiy hisoblagichlar va taqsimotlarni ko‘rish' },
      { code: 'dashboard:view_financials', name: 'Moliyaviy ko‘rsatkichlar', description: 'Balans, jami qiymat va xarajatlar tahlili' },
    ],
  },
  {
    id: 'inbox',
    name: 'Mening Vazifalarim (Action Center)',
    description: 'Xodimga imzolash yoki tasdiqlash uchun yo‘naltirilgan topshiriqlar',
    pageCode: 'page:inbox',
    permissions: [
      { code: 'page:inbox', name: 'Sahifaga kirish', description: 'Vazifalarim sahifasiga kirish huquqi', isPage: true },
      { code: 'inbox:sign', name: 'Hujjatlarni imzolash', description: 'Hujjat va talabnomalarni tasdiqlash hamda imzolash' },
      { code: 'inbox:reject', name: 'Rad etish', description: 'Kelib tushgan talabnomalarni sabab ko‘rsatib rad etish' },
    ],
  },
  {
    id: 'assets',
    name: 'Asosiy Vositalar (Fixed Assets)',
    description: 'Barcha asosiy vositalar reestri, kirim, pasport va QR boshqaruvi',
    pageCode: 'page:assets',
    permissions: [
      { code: 'page:assets', name: 'Sahifaga kirish', description: 'Asosiy vositalar sahifasiga kirish huquqi', isPage: true },
      { code: 'assets:read', name: 'Ro‘yxatni ko‘rish', description: 'Asosiy vositalar ro‘yxati va ma’lumotlarini ko‘rish' },
      { code: 'assets:create', name: 'Yangi kiritish (Kirim)', description: 'Yangi asosiy vositani ro‘yxatga olish' },
      { code: 'assets:update', name: 'Tahrirlash', description: 'Asosiy vosita parametrlari va holatini tahrirlash' },
      { code: 'assets:delete', name: 'Hisobdan chiqarish / O‘chirish', description: 'Aktivni hisobdan chiqarishga berish yoki o‘chirish' },
      { code: 'assets:export', name: 'Excelga eksport', description: 'Aktivlar ro‘yxatini Excel formatida yuklab olish' },
      { code: 'assets:print_qr', name: 'QR-Stiker chop etish', description: 'Asosiy vosita QR kod yorliqlarini chop etish' },
      { code: 'assets:import', name: 'Excel import', description: 'Excel fayl orqali ommaviy aktivlarni kiritish' },
    ],
  },
  {
    id: 'warehouse',
    name: 'Sarflanuvchi Materiallar Ombori',
    description: 'Ombor tovarlari, qoldiqlar, kantselyariya va chiqim boshqaruvi',
    pageCode: 'page:warehouse',
    permissions: [
      { code: 'page:warehouse', name: 'Sahifaga kirish', description: 'Ombor sahifasiga kirish huquqi', isPage: true },
      { code: 'warehouse:read', name: 'Qoldiqlarni ko‘rish', description: 'Ombor tovarlari va joriy qoldiqlarni ko‘rish' },
      { code: 'warehouse:create', name: 'Kirim qilish', description: 'Yangi sarflanuvchi materialni omborga qabul qilish' },
      { code: 'warehouse:update', name: 'Tahrirlash', description: 'Tovar parametrlari va narxlarini yangilash' },
      { code: 'warehouse:delete', name: 'O‘chirish / Spisanie', description: 'Ombor qoldiqlarini o‘chirish yoki yaroqsiz deb topish' },
      { code: 'warehouse:issue', name: 'Chiqim qilish (Tarqatish)', description: 'Xodim va kafedralarga materiallarni tarqatish' },
      { code: 'warehouse:export', name: 'Excelga eksport', description: 'Ombor qoldiqlarini Excel formatida eksport qilish' },
    ],
  },
  {
    id: 'suppliers',
    name: 'Ta’minotchilar va Kontragentlar',
    description: 'Yetkazib beruvchi tashkilotlar, shartnomalar va hisob-kitoblar',
    pageCode: 'page:suppliers',
    permissions: [
      { code: 'page:suppliers', name: 'Sahifaga kirish', description: 'Ta’minotchilar sahifasiga kirish huquqi', isPage: true },
      { code: 'suppliers:read', name: 'Ko‘rish', description: 'Ta’minotchilar va shartnomalar reestrini ko‘rish' },
      { code: 'suppliers:create', name: 'Qo‘shish', description: 'Yangi ta’minotchi yoki shartnomani kiritish' },
      { code: 'suppliers:update', name: 'Tahrirlash', description: 'Ta’minotchi rekvizitlari va shartnomalarini o‘zgartirish' },
      { code: 'suppliers:delete', name: 'O‘chirish', description: 'Ta’minotchini ro‘yxatdan chiqarish' },
    ],
  },
  {
    id: 'movements',
    name: 'Harakatlar Tarixi (Movements Ledger)',
    description: 'Barcha kirim, chiqim, ko‘chirish va qaytarish tranzaksiyalari',
    pageCode: 'page:movements',
    permissions: [
      { code: 'page:movements', name: 'Sahifaga kirish', description: 'Harakatlar jurnali sahifasiga kirish huquqi', isPage: true },
      { code: 'movements:read', name: 'Jurnalni ko‘rish', description: 'Barcha o‘tkazmalar va tranzaksiyalarni ko‘rish' },
      { code: 'movements:print_doc', name: 'Dalolatnomalar (OS-1, OS-2)', description: 'Rasmiy kirim va ichki ko‘chirish hujjatlarini chop etish' },
      { code: 'movements:export', name: 'Excelga eksport', description: 'Tranzaksiyalar tarixini Excel formatida yuklab olish' },
    ],
  },
  {
    id: 'requests',
    name: 'Talabnomalar va Ehtiyojlar Oqimi',
    description: 'Xodimlarning moddiy ehtiyoj talabnomalari va tasdiqlash bosqichlari',
    pageCode: 'page:requests',
    permissions: [
      { code: 'page:requests', name: 'Sahifaga kirish', description: 'Talabnomalar sahifasiga kirish huquqi', isPage: true },
      { code: 'requests:read', name: 'Talabnomalarni ko‘rish', description: 'Barcha kelib tushgan talabnomalarni ko‘rish' },
      { code: 'requests:create', name: 'Yangi talabnoma berish', description: 'Yangi sarf materiali yoki jihoz uchun ariza yaratish' },
      { code: 'requests:update', name: 'Tahrirlash / Bekor qilish', description: 'O‘z talabnomasini o‘zgartirish yoki bekor qilish' },
      { code: 'requests:approve', name: 'Tasdiqlash (Viza qo‘yish)', description: 'Mudir, omborchi, prorektor va rektor darajasida tasdiqlash' },
      { code: 'requests:fulfill', name: 'Bajarish (Ombordan berish)', description: 'Tasdiqlangan talabnoma bo‘yicha tovarlarni topshirish' },
    ],
  },
  {
    id: 'repairs',
    name: 'Ta’mirlash va Texnik Servis',
    description: 'Nosoz jihozlarni ta’mirlash arizalari, xizmat ko‘rsatish va qabul qilish',
    pageCode: 'page:repairs',
    permissions: [
      { code: 'page:repairs', name: 'Sahifaga kirish', description: 'Ta’mirlash sahifasiga kirish huquqi', isPage: true },
      { code: 'repairs:read', name: 'Arizalarni ko‘rish', description: 'Texnik ta’mirlash arizalarini ko‘rish' },
      { code: 'repairs:create', name: 'Ariza berish', description: 'Nosoz uskuna bo‘yicha servis arizasini kiritish' },
      { code: 'repairs:update', name: 'Holatni yangilash', description: 'Diagnostika xulosasi va ta’mirlash jarayonini yuritish' },
      { code: 'repairs:approve', name: 'Qabul qilish / Yopish', description: 'Ta’mirlangan uskunani qabul qilish va dalolatnomani tasdiqlash' },
    ],
  },
  {
    id: 'write_offs',
    name: 'Hisobdan Chiqarish (OS-4 Spisanie)',
    description: 'Yaroqsiz asosiy vositalarni hisobdan chiqarish komissiyasi va aktlar',
    pageCode: 'page:write_offs',
    permissions: [
      { code: 'page:write_offs', name: 'Sahifaga kirish', description: 'Spisanie sahifasiga kirish huquqi', isPage: true },
      { code: 'write_offs:read', name: 'Arizalarni ko‘rish', description: 'Spisanie arizalari va komissiya xulosalarini ko‘rish' },
      { code: 'write_offs:create', name: 'Yangi ariza yaratish', description: 'Aktivni hisobdan chiqarishga taqdim etish' },
      { code: 'write_offs:vote', name: 'Ovoz berish', description: 'Komissiya a’zosi sifatida ovoz berish va imzolash' },
      { code: 'write_offs:print', name: 'OS-4 Aktini chop etish', description: 'Rasmiy davlat standarti bo‘yicha OS-4 dalolatnomasini generatsiya qilish' },
    ],
  },
  {
    id: 'depreciation',
    name: 'Amortizatsiya Dvigateli',
    description: 'Asosiy vositalar eskirish qiymatini avtomatlashtirilgan hisoblash',
    pageCode: 'page:depreciation',
    permissions: [
      { code: 'page:depreciation', name: 'Sahifaga kirish', description: 'Amortizatsiya sahifasiga kirish huquqi', isPage: true },
      { code: 'depreciation:read', name: 'Hisoblarni ko‘rish', description: 'Oylik eskirish stavkalari va qoldiq qiymatlarni ko‘rish' },
      { code: 'depreciation:execute', name: 'Amortizatsiyani ishga tushirish', description: 'Oylik amortizatsiyani avtomatik hisoblash va tasdiqlash' },
      { code: 'depreciation:export', name: 'Eksport qilish', description: 'Amortizatsiya hisobotlarini yuklab olish' },
    ],
  },
  {
    id: 'reports',
    name: 'Bosh Hisobchi va Moliya Hisobotlari',
    description: 'OS-1, OS-2 jurnallari, moliyalashtirish manbalari va 1C/UzASBO',
    pageCode: 'page:chief_accountant',
    permissions: [
      { code: 'page:chief_accountant', name: 'Bosh hisobchi sahifasiga kirish', description: 'Bosh hisobchi reestri sahifasiga kirish', isPage: true },
      { code: 'page:funding_reports', name: 'Manbalar hisoboti sahifasiga kirish', description: 'Byudjet va shartnoma mablag‘lari hisobotlariga kirish', isPage: true },
      { code: 'reports:read', name: 'Hisobotlarni ko‘rish', description: 'Davlat reestrlari va manbalar bo‘yicha tahlillarni ko‘rish' },
      { code: 'reports:stamp', name: 'Muhr / Shtamp qo‘yish', description: 'Hujjatlarga bosh hisobchining elektron tasdiq shtampini bosish' },
      { code: 'reports:export', name: '1C / UzASBO eksport', description: '1C va UzASBO buxgalteriya tizimlari uchun ma’lumotlarni eksport qilish' },
    ],
  },
  {
    id: 'audit',
    name: 'Audit va Inventarizatsiya (QR Scanner)',
    description: 'QR-kod orqali tezkor tekshirish, kampaniyalar va INV-19 aktlari',
    pageCode: 'page:audit',
    permissions: [
      { code: 'page:audit', name: 'Audit & Skaner sahifasiga kirish', description: 'Mobil va veb skaner sahifasiga kirish', isPage: true },
      { code: 'page:audit_campaigns', name: 'Audit rejalari sahifasiga kirish', description: 'Rejali inventarizatsiyalar sahifasiga kirish', isPage: true },
      { code: 'audit:scan', name: 'Skanerlash va tekshirish', description: 'Xonalarda QR kod orqali aktivlarni solishtirish' },
      { code: 'audit:read', name: 'Natijalarni ko‘rish', description: 'Ortiqcha va kamomad tahlillari hamda jurnallarni ko‘rish' },
      { code: 'audit:campaign_manage', name: 'Kampaniya yaratish va tasdiqlash', description: 'Audit muddatlari va komissiya a’zolarini belgilash' },
    ],
  },
  {
    id: 'organization',
    name: 'Tashkiliy Tuzilma (Bino, Xona, Kafedra)',
    description: 'Universitet binolari, o‘quv xonalari, laboratoriyalar va kafedralar',
    pageCode: 'page:organization',
    permissions: [
      { code: 'page:organization', name: 'Sahifaga kirish', description: 'Tashkiliy tuzilma sahifasiga kirish huquqi', isPage: true },
      { code: 'organization:read', name: 'Tuzilmani ko‘rish', description: 'Fakultet, kafedra, bino va xonalar ro‘yxatini ko‘rish' },
      { code: 'organization:manage', name: 'Boshqarish (Qo‘shish/Tahrirlash)', description: 'Yangi xona, bino yoki kafedra qo‘shish va tahrirlash' },
      { code: 'organization:assign_mol', name: 'MOL biriktirish', description: 'Xonalarga moddiy javobgar shaxslarni tayinlash' },
    ],
  },
  {
    id: 'quotas',
    name: 'Kafedralar Kvotasi (Oylik Limitlar)',
    description: 'Kafedralarning kantselyariya va sarf materiallari oylik limitlari',
    pageCode: 'page:quotas',
    permissions: [
      { code: 'page:quotas', name: 'Sahifaga kirish', description: 'Kvotalar sahifasiga kirish huquqi', isPage: true },
      { code: 'quotas:read', name: 'Kvotalarni ko‘rish', description: 'Kafedralar qoldiq limitlari va sarfini ko‘rish' },
      { code: 'quotas:manage', name: 'Limitlarni belgilash', description: 'Yangi oylik limitlarni kiritish va o‘zgartirish' },
    ],
  },
  {
    id: 'users',
    name: 'Foydalanuvchilar va Kirish Huquqlari',
    description: 'Xodimlar hisobi, lavozimlar, parollar va granular ruxsatlar',
    pageCode: 'page:users',
    permissions: [
      { code: 'page:users', name: 'Sahifaga kirish', description: 'Foydalanuvchilar sahifasiga kirish huquqi', isPage: true },
      { code: 'users:read', name: 'Xodimlarni ko‘rish', description: 'Foydalanuvchilar ro‘yxati va ma’lumotlarini ko‘rish' },
      { code: 'users:create', name: 'Yangi xodim qo‘shish', description: 'Yangi foydalanuvchi hisobini yaratish' },
      { code: 'users:update', name: 'Tahrirlash', description: 'Xodim ma’lumotlari va lavozimini o‘zgartirish' },
      { code: 'users:reset_password', name: 'Parolni tiklash', description: 'Xodim parolini vaqtinchalik parolga yangilash' },
      { code: 'users:delete', name: 'O‘chirish / Bloklash', description: 'Xodimni tizimdan o‘chirish yoki nofaol qilish' },
      { code: 'users:permissions', name: 'Ruxsatlarni sozlash (Permissions)', description: 'Foydalanuvchiga granular huquqlar va sahifalarni biriktirish' },
    ],
  },
  {
    id: 'system_audit',
    name: 'Tizim Auditi va Xavfsizlik Jurnali',
    description: 'Kim qachon qaysi amalni bajargani haqidagi barcha xavfsizlik loglari',
    pageCode: 'page:system_audit',
    permissions: [
      { code: 'page:system_audit', name: 'Sahifaga kirish', description: 'Tizim auditi sahifasiga kirish huquqi', isPage: true },
      { code: 'system_audit:read', name: 'Loglarni ko‘rish', description: 'Barcha audit va xavfsizlik yozuvlarini tahlil qilish' },
      { code: 'system_audit:export', name: 'Loglarni eksport qilish', description: 'Xavfsizlik auditini faylga saqlab olish' },
    ],
  },
  {
    id: 'integrations',
    name: 'HEMIS va 1C / UzASBO Integratsiyalari',
    description: 'Davlat axborot tizimlari bilan avtomatik API shlyuzlari',
    pageCode: 'page:integrations',
    permissions: [
      { code: 'page:integrations', name: 'Sahifaga kirish', description: 'Integratsiyalar sahifasiga kirish huquqi', isPage: true },
      { code: 'integrations:read', name: 'Holatni ko‘rish', description: 'API sinxronizatsiya loglari va parametrlarini ko‘rish' },
      { code: 'integrations:sync', name: 'Sinxronizatsiyani ishga tushirish', description: 'HEMIS yoki 1C dan ma’lumotlarni qo‘lda yangilash' },
    ],
  },
  {
    id: 'backups',
    name: 'Zaxira Nusxalari (Backup & Recovery)',
    description: 'Ma’lumotlar bazasi zaxiralari va falokatdan tiklash (Disaster Recovery)',
    pageCode: 'page:backups',
    permissions: [
      { code: 'page:backups', name: 'Sahifaga kirish', description: 'Zaxira nusxalari sahifasiga kirish huquqi', isPage: true },
      { code: 'backups:read', name: 'Zaxiralarni ko‘rish', description: 'Mavjud zaxira fayllari va sanalarini ko‘rish' },
      { code: 'backups:create', name: 'Yangi zaxira yaratish', description: 'Baza zaxira nusxasini qo‘lda shakllantirish' },
      { code: 'backups:restore', name: 'Qayta tiklash', description: 'Tizimni zaxira nusxasidan qayta tiklash' },
    ],
  },
];

export const ALL_PERMISSION_CODES: string[] = PERMISSION_MODULES.flatMap((mod) =>
  mod.permissions.map((p) => p.code),
);

/**
 * Universitet administratori (ADMIN) ko'ra olmaydigan va boshqara olmaydigan
 * faqat SUPER_ADMIN ga tegishli tizim modullari va ruxsat kodlari
 */
export const SUPER_ADMIN_ONLY_MODULE_IDS: string[] = [
  'system_audit',
  'integrations',
  'backups',
];

export const SUPER_ADMIN_ONLY_PERMISSION_CODES: string[] = PERMISSION_MODULES
  .filter((mod) => SUPER_ADMIN_ONLY_MODULE_IDS.includes(mod.id))
  .flatMap((mod) => mod.permissions.map((p) => p.code));

/**
 * Har bir rol uchun tavsiya etiladigan standart ruxsatlar matritsasi (Presets)
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleType, string[]> = {
  [RoleType.SUPER_ADMIN]: ALL_PERMISSION_CODES,

  [RoleType.ADMIN]: [
    'page:dashboard',
    'dashboard:view_stats',
    'dashboard:view_financials',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:create',
    'assets:update',
    'assets:delete',
    'assets:export',
    'assets:print_qr',
    'assets:import',
    'page:warehouse',
    'warehouse:read',
    'warehouse:create',
    'warehouse:update',
    'warehouse:delete',
    'warehouse:issue',
    'warehouse:export',
    'page:suppliers',
    'suppliers:read',
    'suppliers:create',
    'suppliers:update',
    'suppliers:delete',
    'page:movements',
    'movements:read',
    'movements:print_doc',
    'movements:export',
    'page:requests',
    'requests:read',
    'requests:create',
    'requests:update',
    'requests:approve',
    'requests:fulfill',
    'page:repairs',
    'repairs:read',
    'repairs:create',
    'repairs:update',
    'repairs:approve',
    'page:write_offs',
    'write_offs:read',
    'write_offs:create',
    'write_offs:vote',
    'write_offs:print',
    'page:depreciation',
    'depreciation:read',
    'depreciation:execute',
    'depreciation:export',
    'page:chief_accountant',
    'page:funding_reports',
    'reports:read',
    'reports:stamp',
    'reports:export',
    'page:audit',
    'page:audit_campaigns',
    'audit:scan',
    'audit:read',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'organization:manage',
    'organization:assign_mol',
    'page:quotas',
    'quotas:read',
    'quotas:manage',
    'page:users',
    'users:read',
    'users:create',
    'users:update',
    'users:reset_password',
    'users:delete',
  ],

  [RoleType.HEAD_WAREHOUSE]: [
    'page:dashboard',
    'dashboard:view_stats',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:create',
    'assets:update',
    'assets:export',
    'assets:print_qr',
    'assets:import',
    'page:warehouse',
    'warehouse:read',
    'warehouse:create',
    'warehouse:update',
    'warehouse:delete',
    'warehouse:issue',
    'warehouse:export',
    'page:suppliers',
    'suppliers:read',
    'suppliers:create',
    'suppliers:update',
    'page:movements',
    'movements:read',
    'movements:print_doc',
    'movements:export',
    'page:requests',
    'requests:read',
    'requests:create',
    'requests:approve',
    'requests:fulfill',
    'page:repairs',
    'repairs:read',
    'repairs:create',
    'repairs:update',
    'page:write_offs',
    'write_offs:read',
    'write_offs:create',
    'write_offs:vote',
    'write_offs:print',
    'page:chief_accountant',
    'reports:read',
    'page:funding_reports',
    'page:audit',
    'audit:scan',
    'audit:read',
    'page:audit_campaigns',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.MOL]: [
    'page:dashboard',
    'dashboard:view_stats',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:export',
    'assets:print_qr',
    'page:requests',
    'requests:read',
    'requests:create',
    'requests:update',
    'page:repairs',
    'repairs:read',
    'repairs:create',
    'page:write_offs',
    'write_offs:read',
    'write_offs:create',
    'page:funding_reports',
    'reports:read',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.AUDITOR]: [
    'page:dashboard',
    'dashboard:view_stats',
    'dashboard:view_financials',
    'page:inbox',
    'page:assets',
    'assets:read',
    'assets:export',
    'page:warehouse',
    'warehouse:read',
    'warehouse:export',
    'page:suppliers',
    'suppliers:read',
    'page:movements',
    'movements:read',
    'movements:export',
    'page:requests',
    'requests:read',
    'page:write_offs',
    'write_offs:read',
    'page:depreciation',
    'depreciation:read',
    'page:chief_accountant',
    'reports:read',
    'page:funding_reports',
    'page:audit',
    'audit:scan',
    'audit:read',
    'page:audit_campaigns',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.CHIEF_ACCOUNTANT]: [
    'page:dashboard',
    'dashboard:view_stats',
    'dashboard:view_financials',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:export',
    'page:warehouse',
    'warehouse:read',
    'warehouse:export',
    'page:suppliers',
    'suppliers:read',
    'page:movements',
    'movements:read',
    'movements:print_doc',
    'movements:export',
    'page:requests',
    'requests:read',
    'requests:approve',
    'page:write_offs',
    'write_offs:read',
    'write_offs:vote',
    'write_offs:print',
    'page:depreciation',
    'depreciation:read',
    'depreciation:execute',
    'depreciation:export',
    'page:chief_accountant',
    'reports:read',
    'reports:stamp',
    'reports:export',
    'page:funding_reports',
    'page:audit_campaigns',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.COMMENDANT]: [
    'page:dashboard',
    'dashboard:view_stats',
    'page:inbox',
    'inbox:sign',
    'page:assets',
    'assets:read',
    'page:requests',
    'requests:read',
    'requests:create',
    'requests:approve',
    'page:repairs',
    'repairs:read',
    'repairs:create',
    'page:organization',
    'organization:read',
    'organization:assign_mol',
  ],

  [RoleType.RECTOR]: [
    'page:dashboard',
    'dashboard:view_stats',
    'dashboard:view_financials',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:export',
    'page:movements',
    'movements:read',
    'page:requests',
    'requests:read',
    'requests:approve',
    'page:write_offs',
    'write_offs:read',
    'write_offs:vote',
    'page:chief_accountant',
    'reports:read',
    'page:funding_reports',
    'page:audit',
    'audit:read',
    'page:audit_campaigns',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.VICE_RECTOR_FINANCE]: [
    'page:dashboard',
    'dashboard:view_stats',
    'dashboard:view_financials',
    'page:inbox',
    'inbox:sign',
    'inbox:reject',
    'page:assets',
    'assets:read',
    'assets:export',
    'page:movements',
    'movements:read',
    'page:requests',
    'requests:read',
    'requests:approve',
    'page:write_offs',
    'write_offs:read',
    'write_offs:vote',
    'page:depreciation',
    'depreciation:read',
    'page:chief_accountant',
    'reports:read',
    'page:funding_reports',
    'page:audit',
    'audit:read',
    'page:audit_campaigns',
    'audit:campaign_manage',
    'page:organization',
    'organization:read',
    'page:quotas',
    'quotas:read',
  ],

  [RoleType.EMPLOYEE]: [
    'page:dashboard',
    'dashboard:view_stats',
    'page:inbox',
    'inbox:sign',
    'page:requests',
    'requests:read',
    'requests:create',
    'requests:update',
    'page:repairs',
    'repairs:read',
    'repairs:create',
    'page:quotas',
    'quotas:read',
  ],
};
